const fallbackSiteUrl = "https://maa-laxmi-travels.showa.online";
const configuredSiteUrl = process.env.NEXT_PUBLIC_SITE_URL?.trim();

const absoluteSiteUrl =
  configuredSiteUrl && /^https?:\/\//i.test(configuredSiteUrl)
    ? configuredSiteUrl
    : fallbackSiteUrl;

const normalizedSiteUrl = absoluteSiteUrl.endsWith("/")
  ? absoluteSiteUrl.slice(0, -1)
  : absoluteSiteUrl;

export const siteBaseUrl = new URL(normalizedSiteUrl).origin;

export const siteConfig = {
  name: "Maa Lakshmi Tour and Travels",
  description:
    "Book trusted local and outstation taxi service with Maa Lakshmi Tour and Travels. Comfortable cars for family trips, weddings, events, and daily travel.",
  phone: "+91 94316 74083",
  email: "maalakshmitourandtravels@gmail.com",
  location: "Patna, Bihar, India",
  officeAddress: {
    streetAddress:
      "Saristabad West Tola, BPSC Colony, Anishabad, Gardanibagh",
    addressLocality: "Patna",
    addressRegion: "Bihar",
    postalCode: "800002",
    addressCountry: "IN",
  },
  geo: {
    latitude: 25.5847664,
    longitude: 85.1147814,
  },
  mapsUrl:
    "https://www.google.com/maps/dir/25.589843,85.1205783/Maa+Lakshmi+Tour+And+Travels,+Saristabad+West+Tola,+BPSC+Colony,+Anishabad,+Gardanibagh,+Patna,+Bihar+800002/@25.5873889,85.1122818,16z/data=!4m10!4m9!1m1!4e1!1m5!1m1!1s0x39ed59003a5bbd63:0xe7792101900d40a2!2m2!1d85.1147814!2d25.5847664!3e0?entry=ttu&g_ep=EgoyMDI2MDUxMC4wIKXMDSoASAFQAw%3D%3D",
  whatsappUrl:
    "https://wa.me/919431674083?text=Hi!%20I%20would%20like%20to%20book%20a%20ride",
  keywords: [
    "Maa Lakshmi Tour and Travels",
    "taxi service in Patna",
    "cab booking in Patna",
    "outstation taxi service",
    "wedding car rental",
    "tour and travels",
    "local taxi booking",
    "airport pickup and drop",
    "family trip cabs",
    "event transport services",
    "car rental in Patna",
    "trusted taxi service",
    "comfortable cars for rent",
    "luxury car rental",
    "affordable taxi service",
    "reliable cab service",
    "24/7 taxi booking",
    "best taxi service in Patna",
    "taxi service for weddings",
    "taxi service for events",
    "taxi service for family trips",
    "taxi service for outstation travel",
    "Patna airport taxi service",
    "Patna airport cab booking",
    "cab service near Patna Junction",
    "one way taxi in Patna",
    "round trip cab booking Patna",
    "Patna to Ranchi cab service",
    "Patna to Gaya taxi booking",
    "Patna to Darbhanga cab",
    "Patna to Varanasi taxi service",
    "Patna to Delhi cab service",
    "Patna to Kolkata taxi booking",
    "Patna to Bodh Gaya cab",
    "Patna to Deoghar taxi service",
    "Patna to Muzaffarpur cab booking",
    "Patna to Purnia taxi",
    "Patna to Nalanda cab service",
    "Patna to Rajgir taxi booking",
    "Patna to Sasaram cab service",
    "Patna to Bhagalpur taxi",
    "Patna to Nepal border taxi",
    "Bihar outstation taxi service",
    "long distance cab booking Bihar",
    "cheap taxi service in Patna",
    "budget cab booking Patna",
    "online taxi booking Patna",
    "instant cab booking Patna",
    "quick cab booking Patna",
    "cab booking app Patna",
    "book cab online Patna",
    "best cab company in Patna",
    "top rated taxi service Patna",
    "safe taxi service in Patna",
    "verified taxi drivers Patna",
    "night taxi service Patna",
    "24 hour cab service Patna",
    "emergency taxi booking",
    "cab booking for airport transfer",
    "airport taxi near me",
    "cab near Patna airport",
    "Patna railway station taxi",
    "railway station pickup Patna",
    "hotel pickup taxi Patna",
    "cab service for tourists in Patna",
    "Bihar tour package taxi",
    "tourist cab service Bihar",
    "sightseeing taxi in Patna",
    "local sightseeing cab Patna",
    "Patna city tour taxi",
    "Bodh Gaya tour cab",
    "Rajgir tour taxi service",
    "Nalanda sightseeing cab",
    "Vaishali tour taxi booking",
    "driver on rent in Patna",
    "monthly cab rental Patna",
    "daily taxi hire Patna",
    "hourly cab rental Patna",
    "full day cab booking Patna",
    "self drive car rental Patna",
    "chauffeur driven car rental Patna",
    "sedan taxi service Patna",
    "SUV rental in Patna",
    "Innova booking in Patna",
    "Innova Crysta rental Patna",
    "Ertiga cab service Patna",
    "tempo traveller rental Patna",
    "tempo traveller for wedding",
    "corporate cab service Patna",
    "employee transport service Patna",
    "office cab service Patna",
    "business travel taxi service",
    "premium cab service Patna",
    "VIP taxi service Patna",
    "executive car rental Patna",
    "luxury wedding car Patna",
    "bridal car rental Patna",
    "car hire for marriage Patna",
    "wedding Innova booking Patna",
    "decorated wedding car rental",
    "wedding transport service Bihar",
    "cab service in Danapur",
    "cab service in Kankarbagh",
    "taxi service in Boring Road Patna",
    "cab booking in Bailey Road",
    "airport taxi in Bihta",
    "cab service in Hajipur",
    "taxi service in Patliputra",
    "cab booking in Ashok Rajpath",
    "cab service in Rajendra Nagar Patna",
    "local cab service near me",
    "taxi booking near me",
    "best tourist places near Patna",
    "Patna to Gaya road trip guide",
    "taxi fare from Patna airport",
    "best time to visit Bodh Gaya",
    "how to book outstation taxi in Patna",
    "top wedding car options in Patna",
    "Patna sightseeing itinerary",
    "Bihar family trip guide"
  ]
};
